# MARKOV CHAINS

In [1]:
# importing the numpy package to deal with matrices and arrays
import numpy as np

In [2]:
# this function takes an argument n - dimension of our n*n square matrix
# and returns an n*n transition probability matrix
def generate_square_probability_matrix(n):
    matrix = 1-np.random.random((n,n))
    matrix = matrix / matrix.sum(axis=1, keepdims=1)
    return matrix.T

In [3]:
# this function returns the theoretical values for Π = [π0 π1 ... πn]
# making use of the theoretical equation for the ergodic matrices Π = Π*Matrix
def find_pi(matrix):
    dimension = matrix.shape[0]
    matrix = matrix - np.eye(dimension)
    for i in range(dimension):
        matrix[0, i] = 1
    P0 = np.zeros((dimension,1))    
    P0[0] = 1
    return np.matmul(np.linalg.inv(matrix),P0)

## Method I: Monte Carlo Simulation Implementation

In [4]:
# find_interval function. takes a sorted array and a number as input, returns the index of
# the last value that is smaller than the number. 
# in order to make function work faster, the function is implented
# to perform a binary search in O(log(n)) time complexity
def find_interval(arr, number, lower, upper):
    middle = (lower + upper) // 2
    if upper == lower:
        return lower
    if arr[middle] < number:
        return find_interval(arr, number, lower=middle+1, upper=upper)
    else:
        return find_interval(arr, number, lower=lower, upper=middle)

# monte carlo method implemenation. takes a matrix and number of steps as input.
# return Π = [π0 π1 ... πn]
# generates random numbers by using the probability distribution of the current_state.
# finds the new_state by using the above find_interval function
# moves to the new_state and makes the count += 1 for this state
# in the end, we normalize the counted values to add up to 1 and therefore give us the expected Π = [π0 π1 ... πn].
def monte_carlo(matrix, n_steps=200000):
    matrix = matrix.T
    dimension = matrix.shape[0]
    interval_matrix = np.zeros((dimension, dimension))
    for i in range(dimension):
        for j in range(dimension):
            interval_matrix[i, j] = sum(matrix[i, 0:j+1])
    counts = np.zeros((dimension,))
    random_number = np.random.random()
    current_state = int(np.random.random()*dimension)
    for i in range(n_steps):
        random_number = np.random.random()
        row = interval_matrix[current_state,]
        new_state = find_interval(row, random_number, 0, len(row)-1)
        counts[new_state] += 1
        current_state = new_state
    return counts / sum(counts)

## Method II: Matrix Multiplication Implementation

In [5]:
# matrix_multiplication_method function, takes a transition probability matrix and erroe as input.
# returns the expected Π = [π0 π1 ... πn].
# at each step, we calculate the absolute error
# if the error is smaller than the error=0.0005, we return the solution
# else, we continue to compute powers of the matrix by using recursion
def matrix_multiplication_method(matrix, error=0.0005):
    dimension = matrix.shape[0]
    random_row = matrix[int(np.random.random()*dimension),]
    err = np.sum(np.absolute(np.mean(matrix, axis=0) - random_row))
    if err < error:
        return np.mean(matrix, axis=0)
    return matrix_multiplication_method(np.matmul(matrix, matrix))

## Running the functions and checking if they give us the correct answers. 

In [6]:
# generating 3 transition probability matrices of dimensions n*n for n = 5, 25, 50.
n1 = 5
n2 = 25
n3 = 50
matrix1 = generate_square_probability_matrix(n1)
matrix2 = generate_square_probability_matrix(n2)
matrix3 = generate_square_probability_matrix(n3)

### n = 5

In [7]:
# this function returns the theoretical values for Π = [π0 π1 ... πn].
# making use of the theoretical equation for the ergodic matrices Π = Π*Matrix
find_pi(matrix1)

array([[0.14487903],
       [0.20144673],
       [0.18420987],
       [0.19731497],
       [0.2721494 ]])

In [8]:
# monte carlo method to find Π = [π0 π1 ... πn].
monte_carlo(matrix1)

array([0.144215, 0.201385, 0.183685, 0.198295, 0.27242 ])

In [9]:
# matrix multiplciation method to find Π = [π0 π1 ... πn].
matrix_multiplication_method(matrix1.T)

array([0.14487782, 0.201447  , 0.18421173, 0.19731386, 0.27214959])

### n = 25

In [10]:
# this function returns the theoretical values for Π = [π0 π1 ... πn].
# making use of the theoretical equation for the ergodic matrices Π = Π*Matrix
find_pi(matrix2)

array([[0.03918586],
       [0.03771146],
       [0.04395481],
       [0.044173  ],
       [0.04178993],
       [0.04163473],
       [0.03502717],
       [0.0428544 ],
       [0.03909858],
       [0.04388551],
       [0.03732905],
       [0.04127214],
       [0.03650179],
       [0.03846046],
       [0.04593108],
       [0.03593472],
       [0.04113279],
       [0.03520741],
       [0.04716188],
       [0.03401868],
       [0.04802747],
       [0.03827981],
       [0.03642183],
       [0.04143306],
       [0.03357237]])

In [11]:
# monte carlo method to find Π = [π0 π1 ... πn].
monte_carlo(matrix2)

array([0.040315, 0.037915, 0.04388 , 0.04358 , 0.042005, 0.040835,
       0.034615, 0.04223 , 0.039045, 0.043975, 0.037135, 0.0414  ,
       0.03726 , 0.038435, 0.04578 , 0.036075, 0.041105, 0.035935,
       0.04778 , 0.033455, 0.048425, 0.038175, 0.036575, 0.040395,
       0.033675])

In [12]:
# matrix multiplciation method to find Π = [π0 π1 ... πn].
matrix_multiplication_method(matrix2.T)

array([0.03918586, 0.03771146, 0.04395481, 0.044173  , 0.04178993,
       0.04163473, 0.03502717, 0.0428544 , 0.03909858, 0.04388551,
       0.03732905, 0.04127214, 0.03650179, 0.03846047, 0.04593108,
       0.03593472, 0.04113279, 0.03520741, 0.04716188, 0.03401868,
       0.04802747, 0.03827981, 0.03642183, 0.04143306, 0.03357237])

### n = 50

In [13]:
# this function returns the theoretical values for Π = [π0 π1 ... πn].
# making use of the theoretical equation for the ergodic matrices Π = Π*Matrix
find_pi(matrix3)

array([[0.0212586 ],
       [0.02090603],
       [0.01872547],
       [0.02086604],
       [0.01890683],
       [0.01759254],
       [0.02129177],
       [0.02225279],
       [0.01901068],
       [0.01953006],
       [0.02027884],
       [0.01834086],
       [0.02211114],
       [0.01859629],
       [0.01870364],
       [0.01758923],
       [0.02068503],
       [0.01992868],
       [0.02020948],
       [0.02042327],
       [0.02031738],
       [0.01879644],
       [0.01785443],
       [0.02140367],
       [0.01953667],
       [0.01873552],
       [0.01971057],
       [0.02070938],
       [0.02120874],
       [0.02052515],
       [0.01828095],
       [0.02096246],
       [0.02187088],
       [0.01958228],
       [0.02017784],
       [0.02142782],
       [0.02039257],
       [0.02334239],
       [0.01868518],
       [0.01722052],
       [0.01818087],
       [0.02182555],
       [0.02153875],
       [0.01830151],
       [0.01893172],
       [0.02014096],
       [0.02221352],
       [0.021

In [14]:
# monte carlo method to find Π = [π0 π1 ... πn].
monte_carlo(matrix3)

array([0.0212  , 0.020885, 0.0193  , 0.02039 , 0.018435, 0.018215,
       0.02131 , 0.02218 , 0.019015, 0.01938 , 0.01968 , 0.018295,
       0.022105, 0.018785, 0.019035, 0.017285, 0.02118 , 0.019335,
       0.020085, 0.020845, 0.02025 , 0.018895, 0.01786 , 0.020865,
       0.019485, 0.019195, 0.019745, 0.020925, 0.02108 , 0.020215,
       0.01808 , 0.021675, 0.021385, 0.019335, 0.02086 , 0.02137 ,
       0.020535, 0.023455, 0.0186  , 0.01725 , 0.01848 , 0.02178 ,
       0.02168 , 0.017795, 0.01898 , 0.020145, 0.022075, 0.022185,
       0.01785 , 0.02103 ])

In [15]:
# matrix multiplciation method to find Π = [π0 π1 ... πn].
matrix_multiplication_method(matrix3.T)

array([0.02125863, 0.02090603, 0.01872546, 0.02086601, 0.0189069 ,
       0.01759259, 0.02129178, 0.02225278, 0.01901067, 0.01953013,
       0.02027883, 0.01834088, 0.02211111, 0.01859623, 0.01870372,
       0.01758924, 0.02068516, 0.01992863, 0.02020944, 0.02042323,
       0.02031739, 0.01879643, 0.01785437, 0.02140365, 0.01953664,
       0.01873551, 0.01971058, 0.0207094 , 0.02120879, 0.02052517,
       0.01828103, 0.02096248, 0.02187088, 0.01958229, 0.0201778 ,
       0.02142782, 0.02039258, 0.02334237, 0.01868511, 0.0172205 ,
       0.01818089, 0.02182555, 0.02153869, 0.01830151, 0.0189317 ,
       0.020141  , 0.02221341, 0.02181767, 0.01824721, 0.02085412])

## COMMENT: Both 2 methods gave approximately the same answers compared to the expected theoretical values. Both for monte carlo method and matrix multiplication method, increasing the number of iterations would make the answers even more accurate. As the number of iterations go to infinity, we would expect to get the same values as in theoretical solution.

## NOW, LET'S MAKE FIRST STATE OF EVERY MATRIX ABSROBING AND CHECK THE RESULTS AGAIN

In [16]:
matrix1[:, 0] = np.eye(n1)[:,0]
matrix2[:, 0] = np.eye(n2)[:,0]
matrix3[:, 0] = np.eye(n3)[:,0]

In [17]:
# this function returns the theoretical values for Π = [π0 π1 ... πn].
# making use of the theoretical equation for the ergodic matrices Π = Π*Matrix
find_pi(matrix1)

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [18]:
# monte carlo method to find Π = [π0 π1 ... πn].
monte_carlo(matrix1)

array([9.9999e-01, 5.0000e-06, 5.0000e-06, 0.0000e+00, 0.0000e+00])

In [19]:
# matrix multiplciation method to find Π = [π0 π1 ... πn].
matrix_multiplication_method(matrix1.T)

array([9.99956771e-01, 9.46063016e-06, 8.89488788e-06, 1.11637169e-05,
       1.37098165e-05])

In [20]:
# this function returns the theoretical values for Π = [π0 π1 ... πn].
# making use of the theoretical equation for the ergodic matrices Π = Π*Matrix
find_pi(matrix2)

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [21]:
# monte carlo method to find Π = [π0 π1 ... πn].
monte_carlo(matrix2)

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# matrix multiplciation method to find Π = [π0 π1 ... πn].
matrix_multiplication_method(matrix2.T)

array([9.99959309e-01, 1.52924062e-06, 1.91651394e-06, 1.89789966e-06,
       1.79345170e-06, 1.78610616e-06, 1.42909990e-06, 1.80789940e-06,
       1.66227400e-06, 1.87515433e-06, 1.59288867e-06, 1.80536160e-06,
       1.59857415e-06, 1.68132281e-06, 1.96356137e-06, 1.45701444e-06,
       1.72926277e-06, 1.48601919e-06, 1.94490356e-06, 1.44126784e-06,
       2.02594558e-06, 1.56140740e-06, 1.57002558e-06, 1.76721284e-06,
       1.36854736e-06])

In [23]:
# this function returns the theoretical values for Π = [π0 π1 ... πn].
# making use of the theoretical equation for the ergodic matrices Π = Π*Matrix
find_pi(matrix3)

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [24]:
# monte carlo method to find Π = [π0 π1 ... πn].
monte_carlo(matrix3)

array([9.99985e-01, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       5.00000e-06, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 5.00000e-06, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 5.00000e-06,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00])

In [25]:
# matrix multiplciation method to find Π = [π0 π1 ... πn].
matrix_multiplication_method(matrix3.T)

array([9.96342154e-01, 7.77826612e-05, 7.11939050e-05, 7.86354181e-05,
       7.18920035e-05, 6.58929665e-05, 7.80004895e-05, 8.18676932e-05,
       7.20202532e-05, 7.12141671e-05, 7.49417107e-05, 6.87314641e-05,
       8.16744729e-05, 6.97811871e-05, 7.13570553e-05, 6.63682688e-05,
       7.80744024e-05, 7.38380536e-05, 7.58937994e-05, 7.55281205e-05,
       7.63618998e-05, 7.14321216e-05, 6.74520720e-05, 8.09804396e-05,
       7.43945301e-05, 6.85546165e-05, 7.36545629e-05, 7.76394322e-05,
       8.03780334e-05, 7.54471797e-05, 6.86355428e-05, 7.78568226e-05,
       8.31440590e-05, 7.20335777e-05, 7.39658816e-05, 7.93086056e-05,
       7.66588937e-05, 8.82455356e-05, 6.93213078e-05, 6.51252718e-05,
       6.82185409e-05, 8.11688883e-05, 7.91986608e-05, 6.73453497e-05,
       7.15853898e-05, 7.63473237e-05, 8.14554044e-05, 8.22806482e-05,
       6.70101941e-05, 7.79566338e-05])

## COMMENT: AS CAN BE CLEARLY SEEN FROM THE CALCULATIONS MAKING THE FIRST STATE ABSORBING MADE MODEL TO ULTIMATELY GET STUCK AT THE STATE 1 AS EXPECTED. 